[package]
name = "collascii"
version = "0.1.0"
authors = ["Evan New-Schmidt <evan@new-schmidt.com>"]
edition = "2018"

[dependencies]
pancurses = "*"
log = "*"
env_logger = "*"
structopt = "*"
thiserror = "1.*"
anyhow = "1.*"
